# Generated by Django 2.2.4 on 2022-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20220212_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='old_dojo'),
        ),
    ]
