# Generated by Django 2.2.4 on 2022-02-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user_like',
            new_name='users_who_like',
        ),
    ]
